# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 712ea0cea0b3880a1e5949eaa154f02c7b019a191b59ce6f429bb58672510fe80e8f48708c8161cb2cc6146ce05f053db45743039419e972a1eafa36f396e863

test:
  secret_key_base: 7f63a416ff47d7f23911d67856880cbef9a7a906a8ef764a303f7d61bb7cf0808099783aa004005ef0f95aeeb5a7b220e428496dd15f35eaa01918e47ee86e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
